global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'relay-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['relay-service:8081']

  - job_name: 'consumer-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['consumer-service:8081']
